# Generated by Django 5.0.3 on 2024-03-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_userprofile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_salonowner',
            field=models.BooleanField(default=False),
        ),
    ]
