# Generated by Django 5.0.3 on 2024-03-13 09:59

import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0004_userprofile_is_salonowner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('perority', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BookingPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/post/')),
                ('address', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('extra', models.JSONField(default={'book': [{'name': 'Fishy'}], 'dates': [], 'days': []}, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('date_create', models.DateField(default=django.utils.timezone.now)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('services', models.ManyToManyField(blank=True, to='salon.services')),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
