# Generated by Django 5.0.3 on 2024-03-15 12:10

import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0008_alter_bookingpost_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['-perority']},
        ),
        migrations.CreateModel(
            name='BookBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('message', models.CharField(blank=True, default='', max_length=5000, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('time', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('date', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('extra', models.JSONField(null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('is_active', models.BooleanField(default=False)),
                ('date_create', models.DateField(default=django.utils.timezone.now)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.bookingpost')),
                ('saloon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saloon', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_create'],
            },
        ),
    ]
