# Generated by Django 5.0.3 on 2024-03-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0009_alter_services_options_bookby'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookby',
            name='cancle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookby',
            name='cancle_reason',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='bookby',
            name='payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookby',
            name='payment_id',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='bookby',
            name='services',
            field=models.ManyToManyField(blank=True, to='salon.services'),
        ),
    ]
