# Generated by Django 5.0.3 on 2024-03-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0010_bookby_cancle_bookby_cancle_reason_bookby_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookby',
            name='date_create',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bookingpost',
            name='date_create',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bookingpost',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
