# Generated by Django 5.0.3 on 2024-03-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0013_delete_appreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookby',
            name='slug',
            field=models.SlugField(blank=True, max_length=1000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bookingpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=1000, null=True, unique=True),
        ),
    ]
