# Generated by Django 5.0.3 on 2024-04-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0014_alter_bookby_slug_alter_bookingpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookby',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
