# Generated by Django 5.0.3 on 2024-04-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0015_bookby_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookby',
            name='price',
            field=models.DecimalField(decimal_places=2, default=40, max_digits=10),
        ),
    ]
