# Generated by Django 5.0.3 on 2024-04-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0016_bookby_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookby',
            name='reject',
            field=models.BooleanField(default=False),
        ),
    ]
