# Generated by Django 5.0.3 on 2024-04-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0017_bookby_reject'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookby',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
