# Generated by Django 5.0.3 on 2024-04-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0018_bookby_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookby',
            name='message',
            field=models.TextField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='bookingpost',
            name='message',
            field=models.TextField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='saloonreview',
            name='message',
            field=models.TextField(blank=True, default='', max_length=5000, null=True),
        ),
    ]
