# Generated by Django 5.0.3 on 2024-04-28 11:02

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0019_alter_bookby_message_alter_bookingpost_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookby',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='0064xxxxxxx format', max_length=128, region='NZ'),
        ),
        migrations.AlterField(
            model_name='bookingpost',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='0064xxxxxxx format', max_length=128, region='NZ'),
        ),
    ]
