# Generated by Django 5.0.3 on 2024-05-01 12:15

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0020_alter_bookby_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookby',
            name='hideforowner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookby',
            name='hideforuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingpost',
            name='bookdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bookingpost',
            name='booktime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='bookingpost',
            name='is_book',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingpost',
            name='is_hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookby',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages={'invalid': 'please reenter your number in 0064xxxxxxxxx format – e.g. 0064217774444'}, help_text='0064xxxxxxx format', max_length=128, region='NZ'),
        ),
        migrations.AlterField(
            model_name='bookingpost',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages={'invalid': 'please reenter your number in 0064xxxxxxxxx format – e.g. 0064217774444'}, help_text='0064xxxxxxx format', max_length=128, region='NZ'),
        ),
    ]
