# Generated by Django 5.0.3 on 2024-05-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0021_bookby_hideforowner_bookby_hideforuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpost',
            name='bookdatetime',
            field=models.DateTimeField(null=True),
        ),
    ]
