# Generated by Django 5.0.3 on 2024-05-28 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0022_bookingpost_bookdatetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('starttime', models.TimeField(null=True)),
                ('endtime', models.TimeField(null=True)),
                ('perority', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-perority'],
            },
        ),
    ]
