# Generated by Django 5.0.3 on 2024-05-28 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0023_timeadvance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=1000, null=True, unique=True)),
                ('email', models.EmailField(blank=True, default='', max_length=120, null=True)),
                ('message', models.TextField(blank=True, default='', max_length=5000, null=True)),
                ('extra', models.JSONField(null=True)),
                ('services', models.ManyToManyField(blank=True, to='salon.services')),
                ('times', models.ManyToManyField(blank=True, to='salon.timeadvance')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
