# Generated by Django 5.0.3 on 2024-05-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0024_advancerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancerequest',
            name='name',
            field=models.CharField(blank=True, default='', max_length=220, null=True),
        ),
    ]
