# Generated by Django 5.0.3 on 2024-05-28 09:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0025_advancerequest_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancerequest',
            name='message',
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='date_create',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='sended',
            field=models.BooleanField(default=False),
        ),
    ]
