# Generated by Django 4.2.7 on 2024-06-11 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_alter_userprofile_webistelink'),
        ('salon', '0027_remove_advancerequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancerequest',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.region'),
        ),
    ]
