# Generated by Django 4.2.7 on 2024-06-24 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_saloontypes'),
        ('salon', '0029_bookingpost_salontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancerequest',
            name='salontype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.saloontypes'),
        ),
    ]
