# Generated by Django 4.2.7 on 2024-06-26 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0030_advancerequest_salontype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingpost',
            name='salontype',
        ),
    ]
