# Generated by Django 5.0.3 on 2024-03-13 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_userprofile_i_answer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='full_name',
            new_name='first_name',
        ),
    ]
