# Generated by Django 5.0.3 on 2024-03-13 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_userprofile_date_join_userprofile_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='created_at',
            new_name='date_joined',
        ),
    ]
