# Generated by Django 5.0.3 on 2024-03-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_userprofile_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='Capture.PNG', null=True, upload_to='profile'),
        ),
    ]
