# Generated by Django 5.0.3 on 2024-04-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_alter_userprofile_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile/capture.png', null=True, upload_to='profile'),
        ),
    ]
