# Generated by Django 5.0.3 on 2024-05-01 12:15

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_alter_userprofile_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages={'invalid': 'please reenter your number in 0064xxxxxxxxx format – e.g. 0064217774444'}, help_text='0064xxxxxxx format', max_length=128, region=None, unique=True),
        ),
    ]
