# Generated by Django 4.2.7 on 2024-06-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_region_userprofile_webistelink_userprofile_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='webistelink',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
