# Generated by Django 4.2.7 on 2024-06-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_alter_userprofile_webistelink'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaloonTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('perority', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-perority'],
            },
        ),
    ]
