# Generated by Django 4.2.7 on 2024-06-26 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_saloontypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='saloontypes',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile/capture.png', null=True, upload_to='profile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.saloontypes'),
        ),
    ]
