# Generated by Django 5.0.3 on 2024-03-16 10:15

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutusUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, default='', max_length=5000, null=True)),
                ('comapnay', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=255, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True)),
                ('address', models.CharField(blank=True, default='', max_length=5000, null=True)),
                ('text1_heading', models.CharField(blank=True, default='', max_length=5000, null=True)),
                ('text1_description', models.CharField(blank=True, default='', max_length=5000, null=True)),
                ('text1_description2', models.CharField(blank=True, default='', max_length=5000, null=True)),
                ('text1_images', models.ImageField(upload_to='media/about')),
                ('text2_heading', models.CharField(blank=True, default='', max_length=5000, null=True)),
                ('text2_description', models.CharField(blank=True, default='', max_length=5000, null=True)),
                ('text2_description2', models.CharField(blank=True, default='', max_length=5000, null=True)),
                ('text2_images', models.ImageField(upload_to='media/about')),
                ('date_create', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, default='', max_length=5000, null=True)),
                ('message', models.CharField(blank=True, default='', max_length=5000, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=255, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('date_create', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('message', models.CharField(blank=True, default='', max_length=5000, null=True)),
                ('date_create', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
