# Generated by Django 5.0.3 on 2024-04-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glow', '0002_alter_appreview_options_appreview_bid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutusus',
            name='logoimage',
            field=models.ImageField(default='logo.png', upload_to='media/about'),
            preserve_default=False,
        ),
    ]
