# Generated by Django 5.0.3 on 2024-04-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glow', '0004_rename_comapnay_aboutusus_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutusus',
            name='text2_description',
        ),
        migrations.RemoveField(
            model_name='aboutusus',
            name='text2_description2',
        ),
        migrations.RemoveField(
            model_name='aboutusus',
            name='text2_heading',
        ),
        migrations.RemoveField(
            model_name='aboutusus',
            name='text2_images',
        ),
        migrations.AlterField(
            model_name='aboutusus',
            name='text1_description',
            field=models.TextField(blank=True, default='', max_length=5000, null=True),
        ),
    ]
