# Generated by Django 5.0.3 on 2024-04-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glow', '0005_remove_aboutusus_text2_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appreview',
            name='message',
            field=models.TextField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.TextField(blank=True, default='', max_length=5000, null=True),
        ),
    ]
