# Generated by Django 5.0.3 on 2024-04-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glow', '0006_alter_appreview_message_alter_contactus_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutusus',
            name='text1_description2',
            field=models.TextField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='aboutusus',
            name='text1_heading',
            field=models.TextField(blank=True, default='', max_length=5000, null=True),
        ),
    ]
