# Generated by Django 5.0.3 on 2024-05-01 12:15

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glow', '0008_alter_aboutusus_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutusus',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages={'invalid': 'please reenter your number in 0064xxxxxxxxx format – e.g. 0064217774444'}, help_text='0064xxxxxxx format', max_length=128, region='NZ', unique=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages={'invalid': 'please reenter your number in 0064xxxxxxxxx format – e.g. 0064217774444'}, help_text='0064xxxxxxx format', max_length=128, region='NZ', unique=True),
        ),
    ]
