# Generated by Django 5.0.3 on 2024-05-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glow', '0009_alter_aboutusus_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutusus',
            name='fburl',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='aboutusus',
            name='instaurl',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
